# Generated by Django 3.2.4 on 2021-06-06 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fps', 'FPS'), ('rpg', 'RPG'), ('racing', 'Racing'), ('sports', 'Sports')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('stripe', 'Stripe')], max_length=15)),
                ('customer_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('aed', 'aed'), ('afn', 'afn'), ('all', 'all'), ('amd', 'amd'), ('ang', 'ang'), ('aoa', 'aoa'), ('ars', 'ars'), ('aud', 'aud'), ('awg', 'awg'), ('azn', 'azn'), ('bam', 'bam'), ('bbd', 'bbd'), ('bdt', 'bdt'), ('bgn', 'bgn'), ('bif', 'bif'), ('bmd', 'bmd'), ('bnd', 'bnd'), ('bob', 'bob'), ('brl', 'brl'), ('bsd', 'bsd'), ('bwp', 'bwp'), ('bzd', 'bzd'), ('cad', 'cad'), ('cdf', 'cdf'), ('chf', 'chf'), ('clp', 'clp'), ('cny', 'cny'), ('cop', 'cop'), ('crc', 'crc'), ('cve', 'cve'), ('czk', 'czk'), ('djf', 'djf'), ('dkk', 'dkk'), ('dop', 'dop'), ('dzd', 'dzd'), ('egp', 'egp'), ('etb', 'etb'), ('eur', 'eur'), ('fjd', 'fjd'), ('fkp', 'fkp'), ('gbp', 'gbp'), ('gel', 'gel'), ('gip', 'gip'), ('gmd', 'gmd'), ('gnf', 'gnf'), ('gtq', 'gtq'), ('gyd', 'gyd'), ('hkd', 'hkd'), ('hnl', 'hnl'), ('hrk', 'hrk'), ('htg', 'htg'), ('huf', 'huf'), ('idr', 'idr'), ('ils', 'ils'), ('inr', 'inr'), ('isk', 'isk'), ('jmd', 'jmd'), ('jpy', 'jpy'), ('kes', 'kes'), ('kgs', 'kgs'), ('khr', 'khr'), ('kmf', 'kmf'), ('krw', 'krw'), ('kyd', 'kyd'), ('kzt', 'kzt'), ('lak', 'lak'), ('lbp', 'lbp'), ('lkr', 'lkr'), ('lrd', 'lrd'), ('lsl', 'lsl'), ('mad', 'mad'), ('mdl', 'mdl'), ('mga', 'mga'), ('mkd', 'mkd'), ('mmk', 'mmk'), ('mnt', 'mnt'), ('mop', 'mop'), ('mro', 'mro'), ('mur', 'mur'), ('mvr', 'mvr'), ('mwk', 'mwk'), ('mxn', 'mxn'), ('myr', 'myr'), ('mzn', 'mzn'), ('nad', 'nad'), ('ngn', 'ngn'), ('nio', 'nio'), ('nok', 'nok'), ('npr', 'npr'), ('nzd', 'nzd'), ('pab', 'pab'), ('pen', 'pen'), ('pgk', 'pgk'), ('php', 'php'), ('pkr', 'pkr'), ('pln', 'pln'), ('pyg', 'pyg'), ('qar', 'qar'), ('ron', 'ron'), ('rsd', 'rsd'), ('rub', 'rub'), ('rwf', 'rwf'), ('sar', 'sar'), ('sbd', 'sbd'), ('scr', 'scr'), ('sek', 'sek'), ('sgd', 'sgd'), ('shp', 'shp'), ('sll', 'sll'), ('sos', 'sos'), ('srd', 'srd'), ('std', 'std'), ('szl', 'szl'), ('thb', 'thb'), ('tjs', 'tjs'), ('top', 'top'), ('try', 'try'), ('ttd', 'ttd'), ('twd', 'twd'), ('tzs', 'tzs'), ('uah', 'uah'), ('ugx', 'ugx'), ('uyu', 'uyu'), ('uzs', 'uzs'), ('vnd', 'vnd'), ('vuv', 'vuv'), ('wst', 'wst'), ('xaf', 'xaf'), ('xcd', 'xcd'), ('xof', 'xof'), ('xpf', 'xpf'), ('yer', 'yer'), ('zar', 'zar'), ('zmw', 'zmw')], max_length=10)),
                ('price_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('ksuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ksuser')),
            ],
            options={
                'unique_together': {('ksuser', 'game')},
            },
        ),
        migrations.AddField(
            model_name='ksuser',
            name='payment_method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.paymentmethod'),
        ),
        migrations.AddField(
            model_name='ksuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gamecategory'),
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.price'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('ksuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ksuser')),
            ],
            options={
                'unique_together': {('ksuser', 'game')},
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('ksuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ksuser')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
            options={
                'unique_together': {('ksuser', 'game', 'order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('name', 'publisher')},
        ),
    ]
